name: ulsr build
on: [pull_request, push]

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-12]
        cc: [gcc, clang]
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Dependencies
        if: startswith(matrix.os, 'ubuntu-')
        run: |
          sudo apt-get update -qyy
          sudo apt install libglfw3-dev libgl-dev

      - name: Build
        run: make CC="${{matrix.cc}}"

      - name: Build gui
        if: startswith(matrix.os, 'ubuntu-')
        run: |
          make clean
          make gui CC="${{matrix.cc}}"
